export const FETCH_CARS_START = 'FETCH_CARS_START';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const SORT_BY_TYPE = 'SORT_BY_TYPE';
export const FILTER_BY_INPUT_TEXT = 'FILTER_BY_INPUT_TEXT';
